### ISSUE TITLE
What should I amend settings.yaml dependencies path to?

### ISSUE THREAD

**Issue by PL450** [StatCan/SLICEmyPDF#1]
I cannot run the code by creating a conda env as there are conflicts.
However, I have already installed all the needed packages for the code in Python-Anaconda.

I am running the code by directly importing slicemypdf.py into my Python session.
Thus how should I modify the pdf_text_path & pdf_html_path in the settings.yaml?

**IMPORTANT!**

Update settings.yaml dependencies path depending on your environment:

pdf_text_path: "/opt/conda/envs/conda-slicemypdf/bin/pdftotext"
pdf_html_path: "/opt/conda/envs/conda-slicemypdf/bin/pdftohtml"

Thank you!

**Comment by PL450** [comment]
I downloaded the pdftotext.exe from the Xpdf command line tools from https://www.xpdfreader.com/download.html

But it doesn't have bbox-layout. Where should I dowload pdftotext.exe from for  bbox-layout?

**Comment by smashhadi** [comment]
SLICEmyPDF uses pdftotext package available in channel conda-forge. You can add the same channels, dependencies required by SLICEmyPDF to your own environment file. Replace the conda virtual environment name to your own -
 pdf_text_path: "/opt/conda/envs/{YOUR-CONDA-ENVIRONMENT}/bin/pdftotext"
